name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn run build

      - name: Run tests
        run: yarn run test

      - name: Create tag based on package.json
        uses: butlerlogic/action-autotag@ade8d2e19bfcd1e6a91272e2849b4bf4c37a67f1
        if: ${{ github.event_name == 'push' }}
        id: autotag
        with:
          tag_prefix: v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: yarn publish
        if: ${{ steps.autotag.outputs.tagcreated == 'yes' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
